#!/bin/sh -eu

test_for_session() {
  eval_in_session "$1" "server-name" &>/dev/null
}

look_for_session() {
  test_for_session "$1" \
    || (echo "Emacs session $1 not found" && exit 1)
}

ensure_session() {
  look_for_session "$1" &>/dev/null \
    || create_new_session "$1"
}

create_new_session() {
  chronic emacs --daemon="$1"
}

eval_in_session() {
  emacsclient -s "$1" -e "$2"
}

session_uptime() {
  look_for_session "$1"
  eval_in_session "$1" "(emacs-uptime)"
}

session_list() {
  # Quite inaccurate
  emacsclient -e "server-socket-dir" \
    | xargs -I{} find {} -type s \
    | xargs -n 1 basename
}

session_client() {
  SESSION="$1"
  shift
  emacsclient -s "$SESSION" "$@"
}

close_session() {
  emacsclient -s "$1" -e "(kill-emacs)"
}

edit_in_session() {
  SESSION="$1"
  shift
  ensure_session "$SESSION"
  session_client "$SESSION" "$@"
}
